apiVersion: apps/v1
kind: Deployment
metadata:
  name: maib-app-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maib-app-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: maib-app-api
    spec:
      containers:
      - name: maib-app
        image: 533267353350.dkr.ecr.eu-central-1.amazonaws.com/maib-app-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
