apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: maib-app-api-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maib-app-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
