apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: maib-app-app-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maib-app-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
